--- 
services:
  coupon-redis:
    image: redis:7.2-alpine
    container_name: coupon-redis
    networks:
      - coupon-network
    ports:
      - "6380:6380"
    command: redis-server --port 6380
      
  coupon-mysql:
    image: ubuntu/mysql:edge
    container_name: coupon-mysql
    networks:
      - coupon-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coupon
      MYSQL_USER: abcd
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
      TZ: UTC
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-init:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  coupon-api:
    image: cloudbreak6th/coupon-api:latest
    # image: coupon-api
    # build:
    #   context: ./coupon-api
    #   dockerfile: Dockerfile
    container_name: coupon-api
    networks:
      - coupon-network
    ports:
      - "8080:8080"
    depends_on:
      - coupon-mysql
      - coupon-redis
    restart: always

  shop-back:
    image: shop-back
    build:
      context: ./shop-back
      dockerfile: Dockerfile
    container_name: shop-back
    networks:
      - coupon-network
    ports:
      - "8082:8082"
    depends_on:
      coupon-mysql:
        condition: service_healthy

  shop-front:
    image: shop-front
    build:
      context: ./shop-front
      dockerfile: Dockerfile
    container_name: shop-front
    networks:
      - coupon-network
    ports:
      - "80:80"
    environment:
#       - REACT_APP_API_URL=http://shop-back:8082
#       - REACT_APP_COUPON_API_URL=http://coupon-api:8080
    depends_on:
      - coupon-api

networks:
  coupon-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
  mysql-init:
    driver: local
